l_f0_j0_position:
  type: effort_controllers/JointPositionController
  joint: l_f0_j0
  pid: {p: 50.0, i: 0.0, d: 0.001}

l_f1_j0_position:
  type: effort_controllers/JointPositionController
  joint: l_f1_j0
  pid: {p: 50.0, i: 0.0, d: 0.001}
